- name: Desplegar Infra con Terraform
  hosts: localhost
  connection: local
  vars_files:
    - envs/prod.yml

  # Exporta credenciales/region
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id | default(omit) }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key | default(omit) }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token | default(omit) }}"
    AWS_PROFILE: "{{ aws_profile | default(omit) }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"

  tasks:
    # ... (tus tasks de ECR login/build/push)
    - name: Init Terraform (con backend)
      community.general.terraform:
        project_path: "{{ playbook_dir }}/.."
        state: present
        force_init: true
        backend_config:
          bucket: "{{ tf_state_bucket }}"
          key: "{{ tf_state_key }}"
          region: "{{ aws_region }}"
          dynamodb_table: "{{ tf_lock_table }}"
        variables:
          aws_region: "{{ aws_region }}"
          aws_profile: "{{ aws_profile | default(omit) }}"
          aws_access_key_id: "{{ aws_access_key_id | default(omit) }}"
          aws_secret_access_key: "{{ aws_secret_access_key | default(omit) }}"
          aws_session_token: "{{ aws_session_token | default(omit) }}"
          # ... (resto de variables de tu infra)
    - name: Apply Terraform
      community.general.terraform:
        project_path: "{{ playbook_dir }}/.."
        state: present
