---
# Ansible Galaxy collections requeridas para el despliegue
# - amazon.aws: ECR (ecr_repository, ecr_login)
# - community.docker: build & push de imágenes (docker_image)
# - community.general: integración con Terraform (community.general.terraform)

collections:
  - name: amazon.aws
    version: ">=6.0.0"
  - name: community.docker
    version: ">=3.4.0"
  - name: community.general
    version: ">=7.0.0"

# Opcional: si prefieres invalidar CloudFront con módulo en vez de AWS CLI, descomenta:
#  - name: community.aws
#    version: ">=6.0.0"
